name: brew build_twopi
on:
  push:
    branches:
      - main
    paths:
      - "twopi.rb"
  pull_request:
    paths:
      - "twopi.rb"

jobs:
  Build_Create_Bottle:
    strategy:
       matrix:
         os: [macos-10.15, macos-11]
    runs-on: ${{ matrix.os }}    
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
    
      - name: Install-dependencies1
        run: |
            brew install cmake open-mpi scalapack wget zlib netcdf hdf5 numpy scipy coreutils llvm libomp gmsh wxPython mpi4py mercurial
      - name: Install-dependencies2
        run: |
             $(brew --prefix)/opt/Python@3/bin/pip3 install six matplotlib Pillow hgapi PyOpenGL netCDF4 h5py PyPDF2 pdfrw future
      - name: Build a bottle using Homebrew
        run: |
            echo ${{ github.head_ref }}
            NEW_VERSION=$(echo ${{ github.head_ref }} | sed 's/[^0-9.]*//g')
            echo ${NEW_VERSION}	
            brew tap piScope/twopi
            brew install -v piscope/twopi/twopi --build-bottle
            brew bottle --verbose --json piscope/twopi/twopi --root-url=https://github.com/piScope/homebrew-TwoPi/releases/download/TwoPi-${NEW_VERSION}
            ls *.bottle.json
            brew bottle --merge --write --no-commit ./$(ls *.bottle.json)
            ls -l

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: '*.bottle.*'

