name: brew buildtest_test
on:
  push:
    branches:
      - main
    paths:
      - "test.rb"
  pull_request:
    paths:
      - "test.rb"

jobs:
  Build_Create_Bottle:
    strategy:
       matrix:
         os: [macos-10.15, macos-11]
    runs-on: ${{ matrix.os }}    
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Build a bottle using Homebrew
        run: |
            echo ${{ github.event.pull_request.repo.owner.login }}
            echo ${{ github.event.pull_request.repo.name }}
            brew tap piScope/twopi
            brew install -v piscope/twopi/test --build-bottle
            brew bottle --verbose --json piscope/twopi/test --root-url=https://github.com/piScope/homebrew-TwoPi/releases/download/Test-0.9.0
            ls -l
            ls *.bottle.json
            brew bottle --merge --write --no-commit ./$(ls *.bottle.json)
            #brew bottle piscope/twopi/test


      - name: Extact Version String
        run: |
          echo "TAG_VERSION=$(echo ${{github.event.release.tag_name}} | sed 's/[^0-9.]*//g')" >> $GITHUB_ENV

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: '*.bottle.*'

