name: brew pr-pull
on:
  pull_request_target:
    types:
      - labeled
jobs:
  pr-pull:
    if: contains(github.event.pull_request.labels.*.name, 'pr-pull-test')
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Set up git
        uses: Homebrew/actions/git-user-config@master

      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

      - name: Pull bottles
        env:
          #HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
          HOMEBREW_GITHUB_API_TOKEN:  ${{ secrets.BREWRELEASETOKEN }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}
        run: |
          echo $GITHUB_REPOSITORY $PULL_REQUEST
          brew pr-pull -v -d --workflow=buildtest_test.yml --tap=$GITHUB_REPOSITORY $PULL_REQUEST

      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ secrets.BREWRELEASETOKEN }}
          branch: next

      - name: Delete branch
        if: github.event.pull_request.head.repo.fork == false
        env:
          BRANCH: ${{ github.event.pull_request.head.ref }}
        run: git push --delete origin $BRANCH